SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `chat_entry`;
DROP TABLE IF EXISTS `chat_members`;
DROP TABLE IF EXISTS `contacts`;
DROP TABLE IF EXISTS `chat`;
DROP TABLE IF EXISTS `users`;
SET FOREIGN_KEY_CHECKS=1;
